// Shared design tokens — Fraunces/Plus Jakarta Sans, warm cream/espresso/gold palette.
export const theme = {
  bg: '#FAF4E7',
  ink: '#3B2417',
  ink2: '#54331F',
  text: '#2A1D14',
  textMuted: '#8B7C68',
  gold: '#C6892E',
  goldDark: '#9C6A1F',
  goldSoft: '#F5E3C0',
  caramel: '#8A5A2B',
  caramelSoft: '#F0E2CC',
  green: '#4C7A3D',
  greenSoft: '#E7EFDD',
  red: '#B23B2E',
  redSoft: '#F7E3DF',
  grey: '#9C907A',
  greySoft: '#F1EBDC',
  surface: '#FFFFFF',
  border: '#EBDFC7',
  radiusLg: 20,
  radiusMd: 14,
  radiusSm: 10,
  shadow: '0 1px 2px rgba(43,26,10,0.05), 0 10px 26px -14px rgba(43,26,10,0.18)',
  fontHeading: 'var(--font-fraunces), serif',
  fontBody: 'var(--font-jakarta), sans-serif',
  fontMono: 'var(--font-plex-mono), monospace',

  // Legacy aliases kept so not-yet-migrated pages (module player, admin content/storage)
  // still render with a close approximation of this palette instead of breaking.
  get inkSoft() { return this.textMuted },
  get slate() { return this.ink },
  get slateSoft() { return this.ink2 },
  get paper() { return this.bg },
  get paperRaised() { return this.surface },
  get line() { return this.border },
  get amber() { return this.gold },
  get amberDeep() { return this.goldDark },
  get amberTint() { return this.goldSoft },
  get greenTint() { return this.greenSoft },
  get locked() { return this.grey },
  get radius() { return this.radiusMd },
}
